# Generated by Django 3.0.8 on 2020-07-12 00:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfilesupload',
            name='upload_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
