# Generated by Django 3.0.8 on 2020-07-15 14:08

from django.db import migrations, models
import web.models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_auto_20200715_1241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photos',
            name='description',
        ),
        migrations.AlterField(
            model_name='photos',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=web.models.pic_path),
        ),
    ]
