# Generated by Django 3.0.8 on 2020-07-15 14:27

from django.db import migrations, models
import web.models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_auto_20200715_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photos',
            name='file',
            field=models.ImageField(blank=True, null=True, upload_to=web.models.pic_path),
        ),
    ]
